### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by egpbos** [mkuzak/estep-checklist#2]
I would like to see some motivation on some of the items. For instance, I can see the benefit of EditorConfig, but it does seem a bit micromanagey. Docker images are very nice as well, but should it be on a checklist or on a bonus-points-list?

**Comment by mkuzak** [comment]
I agree that there needs to be some motivation, but it should not be in the checklist, maybe in kb.
I think EditorConfig is the thing that will save people a lot of time in multi contributor setup. You want to start hacking on the codebase and not this if "this was supposed to be two spaces for a tab or a tab?, what was the line ending again?" and so on.
Docker containers are the only easy way to see if you can build in fresh environment. It does overlap partly with Travis. I think for complex setups this is essential. for single, for example pip or npm installed tools not so much but than you just need to put two lines in your Dockerfile. But even simple tool in the Docker container can be run by someone without thinking about installing virtualenvironments etc.

I'm curious about what others think

**Comment by mkuzak** [comment]
Motivation should be in separate document. I'm closing this issue.
